/**
 * Calendar core (docs/sessions/08-CALENDAR.md §3). Pure and dependency-free so
 * it's testable and shared by the desktop and mobile clients + the server merge.
 * Every calendar item belongs to a TYPE, and every type has an AUDIENCE — that
 * is the whole permission model. The one rule that isn't a plain matrix lookup:
 * a person always sees their OWN time-off item, whatever the audience says.
 */

export type Audience = 'admin' | 'staff' | 'family';

export type CalType = {
  key: string;
  label: string;
  colour: string;
  icon: string;
  isSystem: boolean;
  isDerived: boolean;
  visibleAdmin: boolean;
  visibleStaff: boolean;
  visibleFamily: boolean;
};

export interface CalItem {
  id?: string;
  date: string; // ISO yyyy-mm-dd (starts_on)
  endDate?: string;
  typeKey: string;
  title: string;
  detail?: string;
  timeLabel?: string;
  classroomIds?: string[];
  userId?: string;
  childId?: string;
  status?: 'pending' | 'approved' | 'denied';
  derived?: boolean;
  engine?: boolean; // generated by the COMAR engine (age transitions)
  coverageNote?: string; // engine-computed coverage risk for pending time off
  coverageRoomId?: string; // the requester's room (for "Find cover")
  coverageRoomName?: string;
}

type VisFields = Pick<CalType, 'key' | 'visibleAdmin' | 'visibleStaff' | 'visibleFamily'>;

/**
 * Whether `audience` may see an item of this type. The one rule beyond the
 * matrix: a person always sees an item that is *about them* (their own time-off,
 * their own credential expiry) whatever the audience says.
 */
export function canSee(type: VisFields, audience: Audience, ctx?: { viewerId?: string; item?: CalItem }): boolean {
  const item = ctx?.item;
  if (item && item.userId && ctx?.viewerId && item.userId === ctx.viewerId) return true;
  return audience === 'admin' ? type.visibleAdmin : audience === 'staff' ? type.visibleStaff : type.visibleFamily;
}

/** Filter a merged item list down to what `audience` (a specific viewer) may see. */
export function filterVisible(items: CalItem[], typeByKey: Record<string, VisFields>, audience: Audience, viewerId?: string): CalItem[] {
  return items.filter((item) => {
    const type = typeByKey[item.typeKey];
    if (!type) return false;
    return canSee(type, audience, { viewerId, item });
  });
}

const pad = (n: number) => String(n).padStart(2, '0');
export const isoDate = (y: number, m: number, d: number): string => `${y}-${pad(m + 1)}-${pad(d)}`;

/** A 6-week (42-cell) grid for a month, Sunday-first. `outside` = spill day. */
export function monthCells(year: number, month: number): { iso: string; outside: boolean }[] {
  const first = new Date(year, month, 1);
  const start = new Date(year, month, 1 - first.getDay()); // back up to Sunday
  const out: { iso: string; outside: boolean }[] = [];
  for (let i = 0; i < 42; i++) {
    const d = new Date(start.getFullYear(), start.getMonth(), start.getDate() + i);
    out.push({ iso: isoDate(d.getFullYear(), d.getMonth(), d.getDate()), outside: d.getMonth() !== month });
  }
  return out;
}

/** The 11 built-in type defaults — mirrors migration 031 (source of truth is the DB). */
export const BUILTIN_CAL_TYPES: CalType[] = [
  { key: 'closure', label: 'Closures & holidays', colour: '#E24B4A', icon: '🚫', isSystem: true, isDerived: false, visibleAdmin: true, visibleStaff: true, visibleFamily: true },
  { key: 'trip', label: 'Field trips', colour: '#1D9E75', icon: '🚌', isSystem: true, isDerived: false, visibleAdmin: true, visibleStaff: true, visibleFamily: true },
  { key: 'conference', label: 'Conferences', colour: '#185FA5', icon: '🪑', isSystem: true, isDerived: false, visibleAdmin: true, visibleStaff: true, visibleFamily: true },
  { key: 'event', label: 'Center events', colour: '#D35400', icon: '🎉', isSystem: true, isDerived: false, visibleAdmin: true, visibleStaff: true, visibleFamily: true },
  { key: 'bday_s', label: 'Student birthdays', colour: '#7B4FBB', icon: '🎂', isSystem: true, isDerived: true, visibleAdmin: true, visibleStaff: true, visibleFamily: true },
  { key: 'bday_t', label: 'Staff birthdays', colour: '#534AB7', icon: '🎂', isSystem: true, isDerived: false, visibleAdmin: true, visibleStaff: true, visibleFamily: false },
  { key: 'timeoff', label: 'Time off & coverage', colour: '#EF9F27', icon: '🌴', isSystem: true, isDerived: true, visibleAdmin: true, visibleStaff: false, visibleFamily: false },
  { key: 'training', label: 'Training & PD', colour: '#0F6E56', icon: '📚', isSystem: true, isDerived: false, visibleAdmin: true, visibleStaff: true, visibleFamily: false },
  { key: 'licensing', label: 'Licensing & compliance', colour: '#993C1D', icon: '⚖️', isSystem: true, isDerived: true, visibleAdmin: true, visibleStaff: false, visibleFamily: false },
  { key: 'drill', label: 'Drills', colour: '#5f5e5a', icon: '🧯', isSystem: true, isDerived: false, visibleAdmin: true, visibleStaff: true, visibleFamily: false },
  { key: 'ratio', label: 'Ratio changes', colour: '#854F0B', icon: '⚠️', isSystem: true, isDerived: true, visibleAdmin: true, visibleStaff: true, visibleFamily: false },
];
